[phases.setup]
commands = [
  "npm install",
  "npm run install-client"
]

[phases.build]
dependsOn = ["setup"]
commands = [
  "npm run build-client"
]

[phases.start]
commands = [
  "npm run start-all"
]

[env]
PORT = "8080"
